version: 2.1

jobs:
    prepare:
    steps:
      - checkout
      - run:
        command: git clone https://github.com/samuelLock/superAwesomeHelloWorld.git
        name: checkout-src
      - run:
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
          name: install aws cli
      - run:
          command: curl -Lo /usr/local/bin/ecs-preview https://github.com/aws/amazon-ecs-cli-v2/releases/download/v0.0.7/ecs-preview-darwin-v0.0.7 && chmod +x /usr/local/bin/ecs-preview && ecs-preview --help
          name: install aws ecs cli
    deploy:
    steps:
      - run:
        command: ecs-preview init --project superawesome-helloworld -app helloworld-static --app-type 'Load Balanced Web App' --dockerfile './Dockerfile' --port 5000 --deploy
  
workflows:
  main:
    jobs:
      - prepare
      - deploy