version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run: git clone https://github.com/samuelLock/superAwesomeHelloWorld.git
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install
      - run: ecs-preview init --project superawesome-helloworld -app helloworld-static --app-type 'Load Balanced Web App' --dockerfile './Dockerfile' --port 5000 --deploy
      

workflows:
  main:
    jobs:
      - deploy