version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.0.0

jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run: git clone https://github.com/samuelLock/superAwesomeHelloWorld.git
      - run: chmod +w /usr/local/bin/
      - run: mkdir /usr/local/bin/ecs-preview
      - run: chmod +w /usr/local/bin/ecs-preview
      - run: curl -Lo /usr/local/bin/ecs-preview https://github.com/aws/amazon-ecs-cli-v2/releases/download/v0.0.7/ecs-preview-linux-v0.0.7 && chmod +x /usr/local/bin/ecs-preview && ecs-preview --help
      - run: ecs-preview init --project superawesome-helloworld -app helloworld-static --app-type 'Load Balanced Web App' --dockerfile './Dockerfile' --port 5000 --deploy
      

workflows:
  main:
    jobs:
      - deploy